### ISSUE TITLE
PHP Composer 2.X: Class does not comply with psr-0 autoloading standard.

### ISSUE THREAD

**Issue by Shadowsith** [kensnyder/poly-crypto#8]
I can not install PolyCrypto from Composer any more cause composer 2.x requires a stricter matching between class names and filenames.

**Comment by kensnyder** [comment]
Fixed in [PolyCrypto v2.0.0](https://github.com/kensnyder/poly-crypto/releases/tag/2.0.0).

**Comment by 04cfb1ed** [comment]
Hello, I'm trying to use poly-crypto with composer v2.0.11 and the problem persists.

```
> composer require poly-crypto/poly-crypto
Using version ^2.0 for poly-crypto/poly-crypto
./composer.json has been updated
Running composer update poly-crypto/poly-crypto
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking poly-crypto/poly-crypto (2.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading poly-crypto/poly-crypto (2.0.0)
  - Installing poly-crypto/poly-crypto (2.0.0): Extracting archive

Class PolyCrypto\PolyAES located in project/vendor/poly-crypto/poly-crypto/src\PolyAES.php does not comply with psr-0 autoloading standard. Skipping. 
Class PolyCrypto\PolyBcrypt located in project/vendor/poly-crypto/poly-crypto/src\PolyBcrypt.php does not comply with psr-0 autoloading standard. Skipping.
Class PolyCrypto\PolyDigest located in project/vendor/poly-crypto/poly-crypto/src\PolyDigest.php does not comply with psr-0 autoloading standard. Skipping.
Class PolyCrypto\PolyRand located in project/vendor/poly-crypto/poly-crypto/src\PolyRand.php does not comply with psr-0 autoloading standard. Skipping.
```

Thanks
